### ISSUE TITLE
Don't repeat links for youtube, thingiverse, etc?

### ISSUE THREAD

**Issue by gunnbr** [gunnbr/gthx#45]
May want to change gthx's reply to links so it doesn't follow kthx's format. Instead of repeating the link, use something like:

VanessaE: well I figured if gthx replies, it could say "So and so's link:  Yet another foo bar Thing, by someone."

**Comment by djhenjin** [comment]
Clarification, If I linked https://www.thingiverse.com/thing:1535485 the preferred response would be more like this:

DJHenjin linked to Stringing Test - 4 x 10mm Cubes by kraeger

Or would it be something else?

**Comment by Duckle29** [comment]
gthx still repeats thingiverse links
