### ISSUE TITLE
Include timestamps in YouTube links

### ISSUE THREAD

**Issue by gunnbr** [gunnbr/gthx#48]
From Duckle in #reprap.

Trying to get more details about exactly what the request is.

**Comment by dumle29** [comment]
Hey, just to preserve the timestamp in the url :)

Example: https://youtu.be/tVkz7SO40LM?t=1029

t=1029, makes the video start 1029 seconds in :)

**Comment by Duckle29** [comment]
@gunnbr Here's an example of the problem:

<Duckle> person: https://youtu.be/8ruFVmxf0zs?t=220
<gthx> http://www.youtube.com/watch?v=8ruFVmxf0zs => EEVblog #105 - Electronics Thermal Heatsink Design Tutorial => 1 IRC mentions

person then clicks the link from gthx, and is annoyed with the long intro, where my link has t=220, skipping the long intro.

Personally I don't actually see the need for GTHX to repeat the link, unless gthx takes a while to respond, and therefore might be responding late.

**Comment by gunnbr** [comment]
@Duckle29 The reason gthx repeats the link is because that was kthx's original behavior. My guess is that kthx did this because it also displays the title of the video so it's harder for someone to rickroll. I know that the repeated link is kind of annoying with some clients though, at least with Textual on the Mac, which shows a preview of the video inline in the chat. With that feature, the title reply is unnecessary and actually irritating as you get 2 inline videos for each link posted instead of just one.

**Comment by gunnbr** [comment]
@Duckle29 and actually in the first example link you posted, I see that the title includes "[strong language]". So that and NSFW are indicators that someone may not want to click on that link at work--another reason for gthx to reply with the link and title.

**Comment by Duckle29** [comment]
Oh for sure I think the title and such is really nice. I just don't understand why it has to also repeat the link.

If we use the above example again:
```
<Duckle> person: https://youtu.be/8ruFVmxf0zs?t=220
<gthx> Duckle linked: EEVblog #105 - Electronics Thermal Heatsink Design Tutorial => 2 IRC mentions
```

That's what I meant when I said "I don't see the need to repeat the link"

Alternatively, if the link needs to be repeated, then how about re-adding the time-stamp?

**Comment by gunnbr** [comment]
Sorry--yes! I do plan to add this feature. That's why I filed this bug. :) I think I have it working already, but I ran into some problems with my development environment that have kept me from being able to test it. Hopefully soon...
