### ISSUE TITLE
GTHX is offline?

### ISSUE THREAD

**Issue by Duckle29** [gunnbr/gthx#53]
Hey, gthx is missing from reprap

**Comment by gunnbr** [comment]
Thanks for the report, @Duckle29 . It's back up and running now and I've got the crash log to show me what happened. I just renamed this bug to reflect the actual cause of the failure.

**Comment by gunnbr** [comment]
Looks like the problems started with a ping timeout:

```
[Gthx,client] gthx disconnected : Ping timeout: 250 seconds
[Gthx,client] Unknown command '' 'ERROR' '['Closing Link: XXXXXXXX.us-west-2.compute.amazonaws.com (Ping timeout: 250 seconds)']'
[Gthx,client] [01:55:41] [disconnected at Thu Jan 24 01:55:41 2019]
```
After that, sending the email failed (due to me switching email servers recently) and it looks like there isn't proper exception handling where this failed:

```
  File "/usr/sbin/gthx/gthx.py", line 158, in connectionLost
	self.emailClient.send("%s disconnected" % self.nickname, "%s is disconnected from the server.\n\n%s" % (self.nickname, \
reason))
  File "/usr/sbin/gthx/Email.py", line 38, in send
	s.login(self.user, self.password)
  File "/usr/lib/python2.7/smtplib.py", line 622, in login
	raise SMTPAuthenticationError(code, resp)
smtplib.SMTPAuthenticationError: (535, 'Incorrect authentication data')
```

**Comment by gunnbr** [comment]
Bah. I apparently used the wrong format in my commit, but I just pushed a fix for this.
